# Generated by Django 5.1.4 on 2025-02-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SailingSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'SailingSkills',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CrewMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('skills', models.ManyToManyField(blank=True, to='toerns.sailingskills')),
            ],
            options={
                'db_table': 'CrewMembers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='toerndirectory',
            fields=[
                ('startDate', models.DateField(help_text='date in YYYY-MM-DD format', primary_key=True, serialize=False)),
                ('endDate', models.DateField(blank=True, help_text='date in YYYY-MM-DD format')),
                ('destination', models.CharField(blank=True, max_length=150, null=True)),
                ('georegion', models.CharField(blank=True, help_text='Atlantic, Caribbean, Great Lakes, Pacific', max_length=40, null=True)),
                ('maptable', models.CharField(blank=True, help_text='name of the Google Maps waypoints table', max_length=100, null=True)),
                ('boat', models.CharField(blank=True, max_length=400, null=True)),
                ('miles', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('daysAtSea', models.IntegerField()),
                ('image', models.CharField(blank=True, null=True, max_length=100)),
                ('picturelink', models.CharField(blank=True, max_length=200, null=True)),
                ('crew', models.ManyToManyField(blank=True, related_name='crewToern', to='toerns.crewmembers')),
                ('skipper', models.ManyToManyField(blank=True, related_name='skipperToern', to='toerns.crewmembers')),
            ],
            options={
                'verbose_name_plural': 'Toern Directory',
                'db_table': 'ToernDirectory',
                'managed': True,
            },
        ),
    ]
