# Generated by Django 5.1.4 on 2025-08-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toerns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toerndirectory',
            name='boat',
            field=models.CharField(blank=True, max_length=810, null=True),
        ),
    ]
