# Generated by Django 5.1.4 on 2025-08-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toerns', '0002_alter_toerndirectory_boat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sailingskills',
            options={'managed': True, 'ordering': ['skill'], 'verbose_name_plural': 'Sailing Skills'},
        ),
    ]
